install:
  - set PATH=C:\Ruby25\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - git submodule update --init --recursive
  - cd ext/argon2_wrap
  - ridk exec make

test_script:
  - bundle exec rake
